### ISSUE TITLE
cl_abap_objectdescr->methods always empty

### ISSUE THREAD

**Issue by larshp** [open-abap/open-abap-core#674]
bug

https://github.com/open-abap/open-abap-core/blob/main/src/rtti/cl_abap_objectdescr.clas.abap#L14

**Comment by larshp** [comment]
starting this now, basics first, trying to get [cacumberer](https://github.com/dominikpanzer/cacamber-BDD-for-ABAP) one step further

fields,
- name
- parameters

and calls method get_method_parameter_type()

**Comment by larshp** [comment]
done

**Comment by dominikpanzer** [comment]
hi Lars, I didn't notice you fixed that problem. thanks! but seems like there is another one. :-/ I'll open a ticket.

**Comment by larshp** [comment]
always another problem :)
