### ISSUE TITLE
UNDEFINED variables during transpiler run.

### ISSUE THREAD

**Issue by dominikpanzer** [open-abap/open-abap-core#681]
Hi Lars,

I tried to merge a new branch, now I get these errors already during the transpiler run.
https://github.com/dominikpanzer/cacamber-BDD-for-ABAP/actions/runs/5074020979/jobs/9113744645?pr=8

I increased the versions in the package.json to get the newest releases:
![grafik](https://github.com/open-abap/open-abap-core/assets/54714566/f5d59c88-5e74-4f88-908a-569bdfccc4db)

Did I break anything?

**Comment by larshp** [comment]
I'm not quite sure the unit tests only started triggering from this commit

However, if commiting often, then its easy to track down when something started breaking

![image](https://github.com/open-abap/open-abap-core/assets/5888506/2cd30a04-89dc-4de9-8dc2-2bf29ff95ba0)

undefined types typically occur during downport, which abaplint does

**Comment by larshp** [comment]
-> https://github.com/abaplint/abaplint/pull/3002

**Comment by larshp** [comment]
fixed in 2.101.4

![image](https://github.com/open-abap/open-abap-core/assets/5888506/086d11e4-882e-4cf4-9875-a5aac288f6b1)

**Comment by larshp** [comment]
next problem to tackle is https://github.com/abaplint/transpiler/pull/1233 which I'll release tomorrow

**Comment by dominikpanzer** [comment]
Hi Lars, thanks for your help and sorry for the trouble :-/

> However, if commiting often, then its easy to track down when something started breaking
Linting / testing is currently only activated on the main branch. I will change this, so I can spot the problem myself easier in the future.

**Comment by larshp** [comment]
more now running

![image](https://github.com/open-abap/open-abap-core/assets/5888506/cecff771-c0e2-4c60-8041-20870ebe1887)

**Comment by larshp** [comment]
next = https://github.com/abaplint/transpiler/pull/1234

**Comment by larshp** [comment]
few more running,
![image](https://github.com/open-abap/open-abap-core/assets/5888506/c9fe23ea-e2f5-4d31-bde4-b4cbcf6a33cf)

**Comment by larshp** [comment]
next is downport problem,

![image](https://github.com/open-abap/open-abap-core/assets/5888506/d0c1ca8b-3c33-49d0-b1fb-cd8ec4e96d29)

**Comment by larshp** [comment]
@dominikpanzer can this issue be closed?

**Comment by dominikpanzer** [comment]
sure - thx :-)
