### ISSUE TITLE
Error when using reserved JavaScript word as ABAP variable name

### ISSUE THREAD

**Issue by oblomov-dev** [open-abap/open-abap-core#764]
This abap code:
<img width="500" alt="image" src="https://github.com/open-abap/open-abap-core/assets/102328295/48e12be9-da9e-4a50-b55a-026d72bcd5e3">
Leads to this error:
<img width="500" alt="image" src="https://github.com/open-abap/open-abap-core/assets/102328295/8f02eccd-e920-4250-818e-245a17e7cadc">

https://github.com/abap2UI5/abap2UI5/pull/509

I am sure this does not occur very often, so maybe also not important to fix, but wanted to document it here.

**Comment by larshp** [comment]
add the keyword to https://github.com/choper725/abap2UI5/blob/main/test/abap_transpile.json#L17

**Comment by oblomov-dev** [comment]
solved, it works, thank you
https://github.com/abap2UI5/abap2UI5/pull/509
