### ISSUE TITLE
open-abap unit test breaks after transpiling

### ISSUE THREAD

**Issue by oblomov-dev** [open-abap/open-abap-core#848]
Hi @larshp,

after transpiling to open-abap and running the unit tests i get this error:
https://github.com/abap2UI5/abap2UI5/actions/runs/7928068163/job/21645588187?pr=893
<img width="800" alt="image" src="https://github.com/open-abap/open-abap-core/assets/102328295/c372226a-398e-42e6-b32c-f80447c7c4a9">

This method is failing (also all the other unit tests of this class, but i guess they have the same root cause):
https://github.com/abap2UI5/abap2UI5/blob/0287284940300a0942e5febb8390a8c50b2c1c25/src/01/02/01/z2ui5_cl_core_bind_srv.clas.testclasses.abap#L89

Refactored most of the classes and splitted them into smaller units, but all other classes & unit tests seem to work with open-abap so i can not encircle this problem closer, just these ones are failing. Any hints welcome or if there is something else i can do on my side?

**Comment by larshp** [comment]
reproduced in https://github.com/open-abap/open-abap-core/pull/849

**Comment by larshp** [comment]
@oblomov-dev try again, update everything to latest

**Comment by oblomov-dev** [comment]
https://github.com/abap2UI5/abap2UI5/pull/898

<img width="971" alt="image" src="https://github.com/open-abap/open-abap-core/assets/102328295/6d432808-50fb-4703-9acb-9e6920dab97f">

updated everything and used my latest code. looks very good now 🥳 
Nice, thank you!
